# ansible-playbook prepare_instance.yml
---
- name: Install Git and clone repositories
  hosts: localhost
  become: yes
  vars:
    repo_dir: /home/ubuntu/Documents/PYTHON
    repos:
      - { name: 'alyx', url: 'https://github.com/cortex-lab/alyx.git' }
      - { name: 'iblalyx', url: 'https://github.com/int-brain-lab/iblalyx.git' }
      - { name: 'iblsre', url: 'https://github.com/int-brain-lab/iblsre.git' }

  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Check if repositories exist
      stat:
        path: "{{ repo_dir }}/{{ item.name }}/.git"
      loop: "{{ repos }}"
      register: repo_stats

    - name: Clone repositories that don't exist
      git:
        repo: "{{ item.item.url }}"
        dest: "{{ repo_dir }}/{{ item.item.name }}"
        version: master
      loop: "{{ repo_stats.results }}"
      when: not item.stat.exists
      become_user: ubuntu

- name: Install Docker
  vars:
    repo_dir: /home/ubuntu/Documents/PYTHON
  import_playbook: "{{ repo_dir }}/iblsre/servers/ansible/docker-setup.yaml"

- name: Prepare Linux instance for Alyx
  become: yes
  hosts: localhost
  vars:
    repo_dir: /home/ubuntu/Documents/PYTHON
    log_dir: /var/log/apache2
    hostname: "{{ ansible_hostname }}"
    ip_address: "{{ ansible_default_ipv4.address }}"
    date_time: "{{ ansible_date_time.iso8601 }}"

  tasks:
    - name: Create spacer file
      command: dd if=/dev/zero of=/home/ubuntu/spacer.bin bs=1 count=0 seek=1G
      args:
        creates: /home/ubuntu/spacer.bin

    - name: Ensure log directory exists
      file:
        path: "{{ log_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy logrotate config to log directory
      copy:
        src: "{{ repo_dir }}/iblalyx/deploy/alyxlogrotate.conf"
        dest: "{{ log_dir }}/alyxlogrotate.conf"
        remote_src: yes
        owner: root
        group: root
        mode: '0600'

    - name: Set up crontab
      cron:
        name: "{{ item.name }}"
        minute: "{{ item.minute }}"
        hour: "{{ item.hour }}"
        day: "{{ item.day }}"
        month: "{{ item.month }}"
        weekday: "{{ item.weekday }}"
        job: "{{ item.job }}"
      loop:
        - name: Renew certificates
          minute: "30"
          hour: "1"
          day: "1,15"
          month: "*"
          weekday: "*"
          job: "docker exec alyx /bin/bash {{ repo_dir }}/iblalyx/crons/renew_docker_certs.sh {{ hostname }} > {{ log_dir }}/cert_renew.log 2>&1"
        - name: Rotate logs
          minute: "0"
          hour: "10"
          day: "*"
          month: "*"
          weekday: "1"
          job: "logrotate -vs {{ log_dir }}/logrotate.state {{ log_dir }}/alyxlogrotate.conf"

    - name: Add alias to .bashrc
      blockinfile:
        path: /home/ubuntu/.bashrc
        block: |
          # IBL Alias
          alias docker-bash='docker exec -it alyx_apache /bin/bash'
        marker: "# {mark} ANSIBLE MANAGED BLOCK - IBL ALIAS"
