services:
  django:
    image: internationalbrainlab/alyx_apache:latest
    container_name: alyx_apache
    ports:
      - "8080:8080"
      - "443:443"
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
      - "80:80"
    env_file: .env
    command: >
      bash -c "python /var/www/alyx/alyx/manage.py collectstatic --noinput &&
               /bin/bash ./alyx_cert_renewal.sh &&
               /usr/sbin/apache2ctl -DFOREGROUND"
    restart: always
    volumes:
      - /var/log/apache2:/var/log/apache2
      - /var/log/alyx:/var/log/alyx
      - /etc/letsencrypt:/etc/apache2/ssl
      - ${DJANGO_MEDIA_ROOT:-~/media}:/var/www/alyx/alyx/media
    depends_on:
      - postgres
  postgres:
    image: postgres:17
    container_name: alyx_postgres
    env_file: .env
    volumes:
      - alyx_postgres:/var/lib/postgresql/data
    expose:
      - 5432
volumes:
  alyx_postgres:
