version: '3.1'
services:
  django:
    image: public.ecr.aws/p4h6o9n8/alyx
    container_name: alyx
    ports:
      - "8080:8080"
      - "443:443"
      - "5432:5432"
      - "80:80"
    env_file: environment.env
    command:
      - '/usr/sbin/apache2ctl'
      - '-DFOREGROUND'
    restart: always
    volumes:
      - ~/logs/alyx:/var/log/alyx
      - ~/logs/apache2:/var/log/apache2
      - /etc/letsencrypt:/etc/apache2/ssl
