version: '3.1'
services:
  django:
    image: public.ecr.aws/p4h6o9n8/alyx
    ports:
      - "8000:8000"
      - "2222:2222"
    env_file: environment.env
    command:
      - /bin/bash
      - -c
      - env | grep _ >> /etc/environment && service ssh start && python /var/www/alyx/alyx/manage.py runserver 0.0.0.0:8000
